# Specify a base image
FROM node:alpine

WORKDIR '/app'

# Download and install dependencies
COPY package.json .
RUN npm install

COPY . .

# Tell the image what to do when it strts as a container
CMD ["npm", "run", "start"]
